name: capstone
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: cap_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: capstone
      POSTGRES_USER: capuser
      POSTGRES_PASSWORD: ${DB_PASS}

    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U capuser -d capstone"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cap_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file: [ .env ]
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/capstone
      SPRING_DATASOURCE_USERNAME: capuser
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SERVER_FORWARD_HEADERS_STRATEGY: framework
      SERVER_SERVLET_SESSION_COOKIE_SECURE: "true"
      SERVER_PORT: 8080
    ports:
      - "127.0.0.1:8080:8080"

    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://127.0.0.1:8080/actuator/health" ]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cap_web
    restart: unless-stopped

    depends_on:
        - backend
    ports:
        - "127.0.0.1:3000:80"
    healthcheck:
        test: [ "CMD", "curl", "-fsS", "http://127.0.0.1:3000" ]
        interval: 15s
        timeout: 3s
        retries: 10
        start_period: 10s

volumes:
   dbdata: